/root/autodl-tmp/yao/rf_env/lib/python3.10/site-packages/lightning/pytorch/utilities/parsing.py:210: Attribute 'env' is an instance of `nn.Module` and is already saved during checkpointing. It is recommended to ignore them using `self.save_hyperparameters(ignore=['env'])`.
/root/autodl-tmp/yao/rf_env/lib/python3.10/site-packages/lightning/pytorch/utilities/parsing.py:210: Attribute 'policy' is an instance of `nn.Module` and is already saved during checkpointing. It is recommended to ignore them using `self.save_hyperparameters(ignore=['policy'])`.
Provided file name ['data/cvrp/val/100.npz', 'data/ovrp/val/100.npz', 'data/ovrpb/val/100.npz', 'data/ovrpbl/val/100.npz', 'data/ovrpbltw/val/100.npz', 'data/ovrpbtw/val/100.npz', 'data/ovrpl/val/100.npz', 'data/ovrpltw/val/100.npz', 'data/ovrptw/val/100.npz', 'data/vrpb/val/100.npz', 'data/vrpl/val/100.npz', 'data/vrpbltw/val/100.npz', 'data/vrpbtw/val/100.npz', 'data/vrpbl/val/100.npz', 'data/vrpltw/val/100.npz', 'data/vrptw/val/100.npz', 'data/cvrp/val/50.npz', 'data/vrptw/val/50.npz'] not found. Make sure to provide a file in the right path first or unset val_file to generate data automatically instead
No solution file found at data/cvrp/test/100_sol_pyvrp.npz
No solution file found at data/ovrp/test/100_sol_pyvrp.npz
No solution file found at data/ovrpb/test/100_sol_pyvrp.npz
No solution file found at data/ovrpbl/test/100_sol_pyvrp.npz
No solution file found at data/ovrpbltw/test/100_sol_pyvrp.npz
No solution file found at data/ovrpbtw/test/100_sol_pyvrp.npz
No solution file found at data/ovrpl/test/100_sol_pyvrp.npz
No solution file found at data/ovrpltw/test/100_sol_pyvrp.npz
No solution file found at data/ovrptw/test/100_sol_pyvrp.npz
No solution file found at data/vrpb/test/100_sol_pyvrp.npz
No solution file found at data/vrpl/test/100_sol_pyvrp.npz
No solution file found at data/vrpbltw/test/100_sol_pyvrp.npz
No solution file found at data/vrpbtw/test/100_sol_pyvrp.npz
No solution file found at data/vrpbl/test/100_sol_pyvrp.npz
No solution file found at data/vrpltw/test/100_sol_pyvrp.npz
No solution file found at data/vrptw/test/100_sol_pyvrp.npz
Provided file name ['data/cvrp/test/100.npz', 'data/ovrp/test/100.npz', 'data/ovrpb/test/100.npz', 'data/ovrpbl/test/100.npz', 'data/ovrpbltw/test/100.npz', 'data/ovrpbtw/test/100.npz', 'data/ovrpl/test/100.npz', 'data/ovrpltw/test/100.npz', 'data/ovrptw/test/100.npz', 'data/vrpb/test/100.npz', 'data/vrpl/test/100.npz', 'data/vrpbltw/test/100.npz', 'data/vrpbtw/test/100.npz', 'data/vrpbl/test/100.npz', 'data/vrpltw/test/100.npz', 'data/vrptw/test/100.npz', 'data/cvrp/test/50.npz', 'data/vrptw/test/50.npz'] not found. Make sure to provide a file in the right path first or unset test_file to generate data automatically instead
No solution file found at data/cvrp/test/100_sol_pyvrp.npz
15.938791275024414
No solution file found at data/vrptw/test/100_sol_pyvrp.npz
Traceback (most recent call last):
  File "/root/autodl-tmp/yao/Hercules/problems/mt_routefinder_unified/eval.py", line 175, in <module>
    main()
  File "/root/autodl-tmp/yao/Hercules/problems/mt_routefinder_unified/eval.py", line 157, in main
    o = test(policy, td_batch, env, device=device)
  File "/root/autodl-tmp/yao/rf_env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
  File "/root/autodl-tmp/yao/Hercules/problems/mt_routefinder_unified/eval.py", line 63, in test
    out = policy(td, env, phase="test", num_starts=n_start, return_actions=True)
  File "/root/autodl-tmp/yao/rf_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/autodl-tmp/yao/rf_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/yao/rf_env/lib/python3.10/site-packages/rl4co/models/common/constructive/base.py", line 258, in forward
    logits, mask = self.decoder(td, hidden, num_starts)
  File "/root/autodl-tmp/yao/rf_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/autodl-tmp/yao/rf_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/yao/rf_env/lib/python3.10/site-packages/rl4co/models/zoo/am/decoder.py", line 289, in forward
    td = unbatchify(td, num_starts)
  File "/root/autodl-tmp/yao/rf_env/lib/python3.10/site-packages/rl4co/utils/ops.py", line 53, in unbatchify
    x = _unbatchify_single(x, s) if s > 0 else x
  File "/root/autodl-tmp/yao/rf_env/lib/python3.10/site-packages/rl4co/utils/ops.py", line 36, in _unbatchify_single
    return x.view(repeats, s[0] // repeats, *s[1:]).permute(1, 0, *range(2, len(s) + 1))
  File "/root/autodl-tmp/yao/rf_env/lib/python3.10/site-packages/tensordict/utils.py", line 862, in func_as_decorator
    out = func(_self, *args, **kwargs)
  File "/root/autodl-tmp/yao/rf_env/lib/python3.10/site-packages/tensordict/base.py", line 4220, in permute
    result = self._permute(*args, **kwargs)
  File "/root/autodl-tmp/yao/rf_env/lib/python3.10/site-packages/tensordict/_td.py", line 1983, in _permute
    if not np.array_equal(sorted(dims_list), range(len(dims_list))):
  File "/root/autodl-tmp/yao/rf_env/lib/python3.10/site-packages/numpy/_core/numeric.py", line 2541, in array_equal
    return builtins.bool((asanyarray(a1 == a2)).all())
  File "/root/autodl-tmp/yao/rf_env/lib/python3.10/site-packages/numpy/_core/_methods.py", line 73, in _all
    return umr_all(a, axis, dtype, out, keepdims)
KeyboardInterrupt
